// Copyright 2009-present MongoDB, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Generate the config.rs crate declaring constants dependent on CMake configuration options.
fn generate_config_crate() {
    use std::fs;
    use std::path::Path;

    let full = std::env::var("MONGOAC_VERSION_FULL").unwrap_or("0.0.0".to_string());
    println!("cargo:rerun-if-env-changed=MONGOAC_VERSION_FULL");

    let build_type = std::env::var("MONGOAC_CMAKE_BUILD_TYPE").unwrap_or_default();
    println!("cargo:rerun-if-env-changed=MONGOAC_CMAKE_BUILD_TYPE");

    let link_type = std::env::var("MONGOAC_LIBRARY_TYPE").unwrap_or_default();
    println!("cargo:rerun-if-env-changed=MONGOAC_LIBRARY_TYPE");

    // Assume valid SemVer string guarantees: regex not required.
    let without_build = full.split('+').next().unwrap_or(&full);
    let mut core_and_prerelease = without_build.splitn(2, '-');
    let core = core_and_prerelease.next().unwrap_or(without_build);
    let prerelease = core_and_prerelease.next().unwrap_or("");

    // [<major>, <minor>, <patch>]
    let version: Vec<&str> = core.split('.').collect();
    assert!(
        version.len() == 3,
        "MONGOAC_VERSION_FULL does not contain a valid SemVer string: {full}"
    );

    let build_type = match build_type.as_str() {
        "Debug" => "d",
        "Release" | "RelWithDebInfo" | "MinSizeRel" => "r",
        _ => "u",
    };

    let link_type = match link_type.as_str() {
        "shared" => "h",
        "static" => "t",
        _ => "u",
    };

    let file = Path::new(&std::env::var("OUT_DIR").expect("OUT_DIR is unset")).join("config.rs");
    fs::write(
        &file,
        format!(
            "// Generated by src/libmongoac/build.rs.\n\
            \n\
            pub const MONGOAC_VERSION_MAJOR: i32 = {major};\n\
            pub const MONGOAC_VERSION_MINOR: i32 = {minor};\n\
            pub const MONGOAC_VERSION_PATCH: i32 = {patch};\n\
            pub const MONGOAC_VERSION_PRERELEASE: &str = \"{prerelease}\";\n\
            pub const MONGOAC_VERSION_FULL: &str = \"{full}\";\n\
            pub const MONGOAC_BUILD_PLATFORM: &str = \"{build_type}{link_type}\";\n",
            major = version[0],
            minor = version[1],
            patch = version[2],
            prerelease = prerelease,
            full = full,
            build_type = build_type,
            link_type = link_type,
        ),
    )
    .expect("failed to write config.rs");
    println!("cargo:rerun-if-changed=build.rs");
}

fn main() {
    generate_config_crate();
}
