[package]
name = "mongoac"
version = "0.1.0-dev"
edition = "2024"
rust-version = "1.88"
publish = false

exclude = [
  "cmake/**",
  "doc/**",
  "include/**",
]

[dependencies]
mongodb = {
  version = "3.8.0",
  features = [
    # BSON.
    "bson-3",

    # Connection.
    "dns-resolver", # Default.
    "rustls-tls", # Default.

    # Authentication.
    "aws-auth",
    "azure-oidc",
    "gcp-oidc",

    # Compression.
    "snappy-compression",
    "zlib-compression",
    "zstd-compression",
  ],
}
