[package]
name = "mongoac"
edition = "2024"
rust-version = "1.88"
publish = false

exclude = [
  "cmake/**",
  "doc/**",
  "include/**",
  "test/**",
]

[workspace]
members = ["tools/generate-crate-headers"]

[dependencies]
mongodb = {
  version = "3.9.0",
  features = [
    # BSON.
    "bson-3",

    # Connection.
    "dns-resolver", # Default.
    "rustls-tls", # Default.

    # Authentication.
    "aws-auth",
    "azure-oidc",
    "gcp-oidc",

    # Compression.
    "snappy-compression",
    "zlib-compression",
    "zstd-compression",
  ],
}
