// Copyright 2009-present MongoDB, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Generated by src/libmongoac/build.rs.
include!(concat!(env!("OUT_DIR"), "/config.rs"));

#[unsafe(no_mangle)]
pub extern "C" fn mongoac_version_major() -> i32 {
    MONGOAC_VERSION_MAJOR
}

#[unsafe(no_mangle)]
pub extern "C" fn mongoac_version_minor() -> i32 {
    MONGOAC_VERSION_MINOR
}

#[unsafe(no_mangle)]
pub extern "C" fn mongoac_version_patch() -> i32 {
    MONGOAC_VERSION_PATCH
}

#[unsafe(no_mangle)]
pub extern "C" fn mongoac_version_hex() -> i32 {
    MONGOAC_VERSION_MAJOR << 24 | MONGOAC_VERSION_MINOR << 16 | MONGOAC_VERSION_PATCH << 8 | 0
}

#[unsafe(no_mangle)]
pub extern "C" fn mongoac_check_version(
    required_major: i32,
    required_minor: i32,
    required_patch: i32,
) -> bool {
    let major = mongoac_version_major();
    let minor = mongoac_version_minor();
    let patch = mongoac_version_patch();

    major > required_major
        || (major == required_major && minor > required_minor)
        || (major == required_major && minor == required_minor && patch >= required_patch)
}
