// Copyright 2009-present MongoDB, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Generated by src/libmongoac/build.rs.
include!(concat!(env!("OUT_DIR"), "/config.rs"));

use crate::string::StringViewT;

#[unsafe(no_mangle)]
pub extern "C" fn mongoac_version_major() -> i32 {
    MONGOAC_VERSION_MAJOR
}

#[unsafe(no_mangle)]
pub extern "C" fn mongoac_version_minor() -> i32 {
    MONGOAC_VERSION_MINOR
}

#[unsafe(no_mangle)]
pub extern "C" fn mongoac_version_patch() -> i32 {
    MONGOAC_VERSION_PATCH
}

#[unsafe(no_mangle)]
pub extern "C" fn mongoac_version_prerelease() -> StringViewT {
    MONGOAC_VERSION_PRERELEASE.into()
}

#[unsafe(no_mangle)]
pub extern "C" fn mongoac_version() -> StringViewT {
    MONGOAC_VERSION_FULL.into()
}

#[unsafe(no_mangle)]
pub extern "C" fn mongoac_version_hex() -> i32 {
    MONGOAC_VERSION_MAJOR << 24 | MONGOAC_VERSION_MINOR << 16 | MONGOAC_VERSION_PATCH << 8
}

#[unsafe(no_mangle)]
pub extern "C" fn mongoac_check_version(major: i32, minor: i32, patch: i32) -> bool {
    let current_major = MONGOAC_VERSION_MAJOR;
    let current_minor = MONGOAC_VERSION_MINOR;
    let current_patch = MONGOAC_VERSION_PATCH;

    current_major > major
        || (current_major == major && current_minor > minor)
        || (current_major == major && current_minor == minor && current_patch >= patch)
}
