noinst_PROGRAMS += test-load
noinst_PROGRAMS += test-mock-server
noinst_PROGRAMS += test-mongoc-array
noinst_PROGRAMS += test-mongoc-buffer
noinst_PROGRAMS += test-mongoc-client
noinst_PROGRAMS += test-mongoc-client-pool
noinst_PROGRAMS += test-mongoc-collection
noinst_PROGRAMS += test-mongoc-cursor
noinst_PROGRAMS += test-mongoc-database
noinst_PROGRAMS += test-mongoc-gridfs
noinst_PROGRAMS += test-mongoc-gridfs-file-page
noinst_PROGRAMS += test-mongoc-list
noinst_PROGRAMS += test-mongoc-queue
noinst_PROGRAMS += test-mongoc-read-prefs
noinst_PROGRAMS += test-mongoc-rpc
noinst_PROGRAMS += test-mongoc-stream
noinst_PROGRAMS += test-mongoc-uri
noinst_PROGRAMS += test-mongoc-write-concern
noinst_PROGRAMS += test-secondary
noinst_PROGRAMS += test-replica-set
noinst_PROGRAMS += test-sharded-cluster
if HAVE_SSL
noinst_PROGRAMS += test-mongoc-stream-tls
noinst_PROGRAMS += test-replica-set-ssl
endif


TEST_PROGS =
TEST_PROGS += test-mongoc-array
TEST_PROGS += test-mongoc-buffer
TEST_PROGS += test-mongoc-client
TEST_PROGS += test-mongoc-client-pool
TEST_PROGS += test-mongoc-collection
TEST_PROGS += test-mongoc-cursor
TEST_PROGS += test-mongoc-database
TEST_PROGS += test-mongoc-gridfs
TEST_PROGS += test-mongoc-gridfs-file-page
TEST_PROGS += test-mongoc-list
TEST_PROGS += test-mongoc-queue
TEST_PROGS += test-mongoc-read-prefs
TEST_PROGS += test-mongoc-rpc
TEST_PROGS += test-mongoc-stream
TEST_PROGS += test-mongoc-uri
TEST_PROGS += test-mongoc-write-concern
if HAVE_SSL
TEST_PROGS += test-mongoc-stream-tls
endif


if OS_LINUX
TEST_PROGS += $(top_srcdir)/tests/abicheck.sh
endif


TEST_LIBS = libmongoc-priv.la $(BSON_LIBS) $(SHM_LIB)


test_load_SOURCES = $(top_srcdir)/tests/test-load.c
test_load_CPPFLAGS = -I$(top_srcdir)/mongoc $(BSON_CFLAGS)
test_load_LDADD = $(TEST_LIBS)


test_mock_server_SOURCES = $(top_srcdir)/tests/test-mock-server.c
test_mock_server_SOURCES += $(top_srcdir)/tests/mock-server.c
test_mock_server_CPPFLAGS = -I$(top_srcdir)/mongoc $(BSON_CFLAGS)
test_mock_server_LDADD = $(TEST_LIBS) -lpthread


test_mongoc_array_SOURCES = $(top_srcdir)/tests/test-mongoc-array.c
test_mongoc_array_CPPFLAGS = -I$(top_srcdir)/mongoc $(BSON_CFLAGS)
test_mongoc_array_LDADD = $(TEST_LIBS)


test_mongoc_buffer_SOURCES = $(top_srcdir)/tests/test-mongoc-buffer.c
test_mongoc_buffer_CPPFLAGS = -I$(top_srcdir)/mongoc $(BSON_CFLAGS)
test_mongoc_buffer_LDADD = $(TEST_LIBS)


test_mongoc_client_SOURCES = \
	$(top_srcdir)/tests/test-mongoc-client.c \
	$(top_srcdir)/tests/mock-server.c
test_mongoc_client_CPPFLAGS = -I$(top_srcdir)/mongoc $(BSON_CFLAGS)
test_mongoc_client_LDADD = $(TEST_LIBS)


test_mongoc_client_pool_SOURCES = $(top_srcdir)/tests/test-mongoc-client-pool.c
test_mongoc_client_pool_CPPFLAGS = -I$(top_srcdir)/mongoc $(BSON_CFLAGS)
test_mongoc_client_pool_LDADD = $(TEST_LIBS)


test_mongoc_collection_SOURCES = $(top_srcdir)/tests/test-mongoc-collection.c
test_mongoc_collection_CPPFLAGS = -I$(top_srcdir)/mongoc $(BSON_CFLAGS)
test_mongoc_collection_LDADD = $(TEST_LIBS)


test_mongoc_cursor_SOURCES = $(top_srcdir)/tests/test-mongoc-cursor.c
test_mongoc_cursor_CPPFLAGS = -I$(top_srcdir)/mongoc $(BSON_CFLAGS)
test_mongoc_cursor_LDADD = $(TEST_LIBS)


test_mongoc_database_SOURCES = $(top_srcdir)/tests/test-mongoc-database.c
test_mongoc_database_CPPFLAGS = -I$(top_srcdir)/mongoc $(BSON_CFLAGS)
test_mongoc_database_LDADD = $(TEST_LIBS)


test_mongoc_gridfs_SOURCES = $(top_srcdir)/tests/test-mongoc-gridfs.c
test_mongoc_gridfs_CPPFLAGS = -I$(top_srcdir)/mongoc $(BSON_CFLAGS)
test_mongoc_gridfs_LDADD = $(TEST_LIBS)


test_mongoc_gridfs_file_page_SOURCES = $(top_srcdir)/tests/test-mongoc-gridfs-file-page.c
test_mongoc_gridfs_file_page_CPPFLAGS = -I$(top_srcdir)/mongoc $(BSON_CFLAGS)
test_mongoc_gridfs_file_page_LDADD = $(TEST_LIBS)


test_mongoc_list_SOURCES = $(top_srcdir)/tests/test-mongoc-list.c
test_mongoc_list_CPPFLAGS = -I$(top_srcdir)/mongoc $(BSON_CFLAGS)
test_mongoc_list_LDADD = $(TEST_LIBS)


test_mongoc_queue_SOURCES = $(top_srcdir)/tests/test-mongoc-queue.c
test_mongoc_queue_CPPFLAGS = -I$(top_srcdir)/mongoc $(BSON_CFLAGS)
test_mongoc_queue_LDADD = $(TEST_LIBS)


test_mongoc_read_prefs_SOURCES = $(top_srcdir)/tests/test-mongoc-read-prefs.c
test_mongoc_read_prefs_CPPFLAGS = -I$(top_srcdir)/mongoc $(BSON_CFLAGS)
test_mongoc_read_prefs_LDADD = $(TEST_LIBS)


test_mongoc_rpc_SOURCES = $(top_srcdir)/tests/test-mongoc-rpc.c
test_mongoc_rpc_CPPFLAGS = -I$(top_srcdir)/mongoc $(BSON_CFLAGS)
test_mongoc_rpc_LDADD = $(TEST_LIBS)


test_mongoc_stream_SOURCES = $(top_srcdir)/tests/test-mongoc-stream.c
test_mongoc_stream_CPPFLAGS = -I$(top_srcdir)/mongoc $(BSON_CFLAGS)
test_mongoc_stream_LDADD = $(TEST_LIBS)


test_mongoc_stream_tls_SOURCES = \
	$(top_srcdir)/tests/test-mongoc-stream-tls.c \
	$(top_srcdir)/tests/ssl-test.c \
	$(top_srcdir)/tests/ssl-test.h \
	$(top_srcdir)/tests/ha-test.c \
	$(top_srcdir)/tests/ha-test.h
test_mongoc_stream_tls_CPPFLAGS = -I$(top_srcdir)/mongoc $(BSON_CFLAGS)
test_mongoc_stream_tls_LDADD = $(TEST_LIBS)


test_mongoc_uri_SOURCES = $(top_srcdir)/tests/test-mongoc-uri.c
test_mongoc_uri_CPPFLAGS = -I$(top_srcdir)/mongoc $(BSON_CFLAGS)
test_mongoc_uri_LDADD = $(TEST_LIBS)


test_mongoc_write_concern_SOURCES = $(top_srcdir)/tests/test-mongoc-write-concern.c
test_mongoc_write_concern_CPPFLAGS = -I$(top_srcdir)/mongoc $(BSON_CFLAGS)
test_mongoc_write_concern_LDADD = $(TEST_LIBS)


test_secondary_SOURCES = $(top_srcdir)/tests/test-secondary.c
test_secondary_CPPFLAGS = -I$(top_srcdir)/mongoc $(BSON_CFLAGS)
test_secondary_LDADD = $(TEST_LIBS)

test_replica_set_SOURCES = \
	$(top_srcdir)/tests/test-replica-set.c \
	$(top_srcdir)/tests/ha-test.c \
	$(top_srcdir)/tests/ha-test.h
test_replica_set_CPPFLAGS = -I$(top_srcdir)/mongoc $(BSON_CFLAGS)
test_replica_set_LDADD = libmongoc-priv.la


test_replica_set_ssl_SOURCES = \
	$(top_srcdir)/tests/test-replica-set-ssl.c \
	$(top_srcdir)/tests/ha-test.c \
	$(top_srcdir)/tests/ha-test.h
test_replica_set_ssl_CPPFLAGS = -I$(top_srcdir)/mongoc $(BSON_CFLAGS)
test_replica_set_ssl_LDADD = libmongoc-priv.la


test_sharded_cluster_SOURCES = \
	$(top_srcdir)/tests/test-sharded-cluster.c \
	$(top_srcdir)/tests/ha-test.c \
	$(top_srcdir)/tests/ha-test.h
test_sharded_cluster_CPPFLAGS = -I$(top_srcdir)/mongoc $(BSON_CFLAGS)
test_sharded_cluster_LDADD = libmongoc-priv.la

test_certs: $(top_srcdir)/tests/trust_dir/done

$(top_srcdir)/tests/trust_dir/done: $(top_srcdir)/tests/make_ca.pl $(top_srcdir)/tests/trust_dir.cnf
	$< $(top_srcdir)/tests/trust_dir $(top_srcdir)/tests/trust_dir.cnf
	touch $(top_srcdir)/tests/trust_dir/done

if HAVE_SSL
test: $(TEST_PROGS) test_certs
else
test: $(TEST_PROGS)
endif
	@ echo "Checking if MongoDB is available on 27017."
	@ $(NETCAT) 127.0.0.1 27017 </dev/null
	@ for TEST_PROG in $(TEST_PROGS) ; do \
		./$$TEST_PROG ; \
	done

.PHONY: test_certs
