noinst_PROGRAMS =
noinst_PROGRAMS += test-mongoc-client-pool
noinst_PROGRAMS += test-mongoc-event
noinst_PROGRAMS += test-mongoc-list
noinst_PROGRAMS += test-mongoc-queue
noinst_PROGRAMS += test-mongoc-uri


TEST_PROGS =
TEST_PROGS += test-mongoc-client-pool
TEST_PROGS += test-mongoc-event
TEST_PROGS += test-mongoc-list
TEST_PROGS += test-mongoc-queue
TEST_PROGS += test-mongoc-uri


test_mongoc_client_pool_SOURCES = $(top_srcdir)/tests/test-mongoc-client-pool.c
test_mongoc_client_pool_CPPFLAGS = -I$(top_srcdir)/mongoc $(BSON_CFLAGS)
test_mongoc_client_pool_LDADD = libmongoc-1.0.la $(BSON_LIBS)


test_mongoc_event_SOURCES = $(top_srcdir)/tests/test-mongoc-event.c
test_mongoc_event_CPPFLAGS = -I$(top_srcdir)/mongoc $(BSON_CFLAGS)
test_mongoc_event_LDADD = libmongoc-1.0.la $(BSON_LIBS)


test_mongoc_list_SOURCES = $(top_srcdir)/tests/test-mongoc-list.c
test_mongoc_list_CPPFLAGS = -I$(top_srcdir)/mongoc $(BSON_CFLAGS)
test_mongoc_list_LDADD = libmongoc-1.0.la $(BSON_LIBS)


test_mongoc_queue_SOURCES = $(top_srcdir)/tests/test-mongoc-queue.c
test_mongoc_queue_CPPFLAGS = -I$(top_srcdir)/mongoc $(BSON_CFLAGS)
test_mongoc_queue_LDADD = libmongoc-1.0.la $(BSON_LIBS)


test_mongoc_uri_SOURCES = $(top_srcdir)/tests/test-mongoc-uri.c
test_mongoc_uri_CPPFLAGS = -I$(top_srcdir)/mongoc $(BSON_CFLAGS)
test_mongoc_uri_LDADD = libmongoc-1.0.la $(BSON_LIBS)


test: $(TESTS)
	@ for TEST_PROG in $(TEST_PROGS) ; do \
		./$$TEST_PROG ; \
	done
