include:
  - filename: .evergreen/generated_configs/legacy-config.yml
  - filename: .evergreen/generated_configs/functions.yml
  # - filename: .evergreen/generated_configs/post.yml
  # - filename: .evergreen/generated_configs/pre.yml
  - filename: .evergreen/generated_configs/task_groups.yml
  - filename: .evergreen/generated_configs/tasks.yml
  - filename: .evergreen/generated_configs/variants.yml
