// Copyright 2009-present MongoDB, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

use std::path::{Path, PathBuf};

// Keep synchronized with `skip_cargo_headers` in src/libmongoac/CMakeLists.txt.
const SKIP_CARGO_HEADERS: &[&str] = &["lib", "mod", "version"];

// Keep synchronized with `skip_forward_headers` in src/libmongoac/CMakeLists.txt.
const SKIP_FORWARD_HEADERS: &[&str] = &["string"];

// Prelude shared by all generated headers.
fn generate_header() -> String {
    [
        "// Copyright 2009-present MongoDB, Inc.",
        "//",
        "// Licensed under the Apache License, Version 2.0 (the \"License\");",
        "// you may not use this file except in compliance with the License.",
        "// You may obtain a copy of the License at",
        "//",
        "// http://www.apache.org/licenses/LICENSE-2.0",
        "//",
        "// Unless required by applicable law or agreed to in writing, software",
        "// distributed under the License is distributed on an \"AS IS\" BASIS,",
        "// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.",
        "// See the License for the specific language governing permissions and",
        "// limitations under the License.",
        "",
        "// Generated by src/libmongoac/tools/generate-crate-headers/src/main.rs.",
    ]
    .join("\n")
}

// Rename structs from `ExampleT` to `mongoac_example_t`.
fn rename_structs() -> std::collections::HashMap<String, String> {
    let pairs: &[(&str, &str)] = &[
        ("ErrorT", "mongoac_error_t"),
        ("StringT", "mongoac_string_t"),
        ("StringViewT", "mongoac_string_view_t"),
    ];

    pairs
        .iter()
        .map(|(k, v)| (k.to_string(), v.to_string()))
        .collect()
}

// Crate-specific configuration options.
fn configure(name: &str, config: &mut cbindgen::Config) {
    // Include directives required by each crate header.
    {
        let headers: &[&str] = match name {
            "error" => &["mongoac/string.h", "stdint.h"],
            "string" => &["stdint.h"],
            _ => {
                eprintln!("warning: missing generate-crate-headers entry for {name}");
                &[]
            }
        };

        config
            .sys_includes
            .extend(headers.iter().map(|v| v.to_string()));
    }

    // Structs which need to be explicitly exported (due to no exported function referencing the struct).
    {
        let exports: &[&str] = match name {
            "string" => &["StringViewT"],
            _ => &[],
        };

        config
            .export
            .include
            .extend(exports.iter().map(|v| v.to_string()));
    }
}

fn default_config() -> cbindgen::Config {
    cbindgen::Config {
        language: cbindgen::Language::C,
        style: cbindgen::Style::Both,
        header: Some(generate_header()),
        cpp_compat: true,
        braces: cbindgen::Braces::NextLine,
        line_length: 120,
        tab_width: 3,
        documentation: false,
        documentation_style: cbindgen::DocumentationStyle::C99,
        export: cbindgen::ExportConfig {
            rename: rename_structs(),
            ..Default::default()
        },
        function: cbindgen::FunctionConfig {
            prefix: Some("MONGOAC_ABI_EXPORT".to_owned()),
            ..Default::default()
        },
        no_includes: true,
        ..Default::default()
    }
}

fn generate_forward_header(crate_path: &Path, rel_stem: &Path, include_dir: &Path) {
    let rel_str = rel_stem.to_str().expect("invalid UTF-8");

    // `path/to/crate` -> `MONGOAC_PATH_TO_CRATE_FWD_H`
    let include_guard = format!(
        "MONGOAC_{}_FWD_H",
        rel_str
            .replace(std::path::MAIN_SEPARATOR, "_")
            .to_uppercase()
    );

    // `path/to/crate` -> `<include_dir>/path/to/crate-fwd.h`
    // Parent directories are already created by `generate_crate_header()`.
    let header_path = include_dir.join(rel_stem).with_file_name(format!(
        "{}-fwd.h",
        rel_stem
            .file_name()
            .and_then(|s| s.to_str())
            .expect("invalid UTF-8")
    ));

    let config = {
        let mut config = default_config();

        // Only forward declarations of opaque structs.
        config.export.item_types = vec![cbindgen::ItemType::OpaqueItems];

        config
    };

    // Generate the forward header.
    cbindgen::Builder::new()
        .with_config(config)
        .with_include_guard(&include_guard)
        .with_src(crate_path)
        .generate()
        .expect("cbindgen failed")
        .write_to_file(&header_path);
}

fn generate_crate_header(crate_path: &Path, src_dir: &Path, include_dir: &Path) {
    let file_stem = crate_path
        .file_stem()
        .and_then(|s| s.to_str())
        .expect("invalid UTF-8");

    if SKIP_CARGO_HEADERS.contains(&file_stem) {
        return;
    }

    // `src/libmongoac/src/path/to/crate.rs` -> `path/to/crate`
    let rel_path = crate_path
        .strip_prefix(src_dir)
        .expect("file not under src root");
    let rel_stem = rel_path.with_extension("");
    let rel_str = rel_stem.to_str().expect("invalid UTF-8");

    // `path/to/crate` -> `MONGOAC_PATH_TO_CRATE_H`
    let include_guard = format!(
        "MONGOAC_{}_H",
        rel_str
            .replace(std::path::MAIN_SEPARATOR, "_")
            .to_uppercase()
    );

    // `path/to/crate` -> `<include_dir>/path/to/crate.h`
    let header_path = include_dir.join(&rel_stem).with_extension("h");
    if let Some(parent) = header_path.parent() {
        std::fs::create_dir_all(parent)
            .unwrap_or_else(|_| panic!("failed to create include directory: {}", parent.display()));
    }

    // Default cbindgen configuration for all crates.
    let config = {
        let mut config = default_config();

        // All except `OpaqueItems` (which is declared in the forward header).
        config.export.item_types = vec![
            cbindgen::ItemType::Functions,
            cbindgen::ItemType::Typedefs,
            cbindgen::ItemType::Constants,
            cbindgen::ItemType::Enums,
            cbindgen::ItemType::Structs,
            cbindgen::ItemType::Unions,
        ];

        // Always include the component's forward header first.
        if !SKIP_FORWARD_HEADERS.contains(&file_stem) {
            generate_forward_header(crate_path, &rel_stem, include_dir);
            config.sys_includes.push(format!("mongoac/{rel_str}-fwd.h"));
        }

        // Normal headers typically export at least one symbol.
        config.sys_includes.push("mongoac/export.h".into());

        // Apply per-crate configuration options.
        configure(rel_str, &mut config);

        config
    };

    // Generate the crate header.
    cbindgen::Builder::new()
        .with_config(config)
        .with_include_guard(&include_guard)
        .with_src(crate_path)
        .generate()
        .expect("cbindgen failed")
        .write_to_file(&header_path);
}

// Recursively find all mongoac crates under the source directory which need a header.
fn find_crates(dir: &Path, files: &mut Vec<PathBuf>) {
    for entry in std::fs::read_dir(dir)
        .unwrap_or_else(|_| panic!("failed to read directory: {}", dir.display()))
    {
        let path = entry
            .map(|e| e.path())
            .unwrap_or_else(|_| panic!("failed to read directory entry in: {}", dir.display()));

        if path.is_dir() {
            if path.file_name().is_some_and(|name| name == "private") {
                continue; // Private crates do not need headers.
            }

            find_crates(&path, files);
        } else if path.extension().is_some_and(|e| e == "rs") {
            files.push(path);
        }
    }
}

fn main() {
    let src_dir = std::env::var("MONGOAC_SRC_DIR")
        .expect("MONGOAC_SRC_DIR is required (the Rust source root directory)");
    let include_dir = std::env::var("MONGOAC_INCLUDE_DIR")
        .expect("MONGOAC_INCLUDE_DIR is required (the output directory for generated headers)");

    let src_path = Path::new(&src_dir);
    let include_path = Path::new(&include_dir);

    let mut files = Vec::new();
    find_crates(src_path, &mut files);

    // Generate crate headers in parallel.
    let handles = files
        .into_iter()
        .map(|path| {
            let include_dir = include_path.to_path_buf();
            let src_dir = src_path.to_path_buf();

            std::thread::spawn(move || {
                generate_crate_header(&path, &src_dir, &include_dir);
            })
        })
        .collect::<Vec<_>>();
    for handle in handles {
        handle.join().expect("header generation failed");
    }
}
