bin_PROGRAMS =
bin_PROGRAMS += mongoc-stat


mongoc_stat_SOURCES = $(top_srcdir)/tools/mongoc-stat.c
mongoc_stat_CPPFLAGS = -I$(top_srcdir)/mongoc $(BSON_CFLAGS)
mongoc_stat_LDADD = libmongoc-1.0.la $(BSON_LIBS) $(SHM_LIB)
